### ISSUE TITLE
Unable to install the latest version 0.1.6

### ISSUE THREAD

**Issue by NastasiaSaby** [deepmind/tree#43] opened 2021-04-12 13:52 UTC
I receive an error with the new version: 0.1.6 with Python version 3.8.6.

When I try to install dm-tree:

```
pip install dm-tree
```

I receive this error:
 
```
unable to execute 'bazel': No such file or directory
error: command 'bazel' failed with exit status 1
```

I cannot install the latest version. But it works with 0.1.5.

Python version: 3.8.6
dm-tree version: 0.1.6

**Comment by KeithWM** [comment] 2021-04-12 18:38
The same issue arose for me. Behaviour appears to b somewhat unpredictable. When pip downloads 
`dm_tree-0.1.6-cp36-cp36m-manylinux2014_x86_64.whl`, it works, but when attempting to build from `dm-tree-0.1.6.tar.gz`, it fails. Don't know why it chooses differently in different cases of doing essentially the same `pip install -v --no-cache-dir -r requirements.txt`. Doing this within a Docker `FROM tensorflow/tensorflow:2.3.0-gpu`.

**Comment by superbobry** [comment] 2021-04-12 20:37
@NastasiaSaby, are you running linux by any chance?

I originally released the wheels with (a fairly recent) manylinux_2_4 tag which, I assume, does not work on some distros. I've since uploaded manylinux2014 wheels. Could you try installing `dm-tree` again? 

@KeithWM interesting! I've tried uninstalling and installing `dm-tree` locally but couldn't reproduce the behavior you're describing. Could you confirm that the behavior persists if you upgrade `pip` prior to doing `pip install -v ...`?

**Comment by NastasiaSaby** [comment] 2021-04-13 07:37
@superbobry yes, I'm using Linux. It's working this morning when I install dm-tree. Thank you for your help!

@superbobry @KeithWM Can I close the issue?

**Comment by KeithWM** [comment] 2021-04-13 08:22
Thank you very much for the quick response! My builds are now passing again, presumably due to the change by the changes you mention. I was surprised yesterday evening when it worked, but it was the "I can close my laptop now" moment so I ddin't bother thinking why or revisiting this post.

Thanks again. 

Yes, @NastasiaSaby, you can close the issue.

**Closed** 2021-04-13 08:30 UTC
